[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 9

[font.offset]
x = 1
y = 0

[font.normal]
family = "Cascadia Mono"
style = "Regular"

[font.bold]
family = "Cascadia Mono"
style = "Bold"

[font.italic]
family = "Cascadia Mono"
style = "Italic"

[font.bold_italic]
family = "Cascadia Mono"
style = "Bold Italic"
